# Zielsetzung {.unlisted .unnumbered}


Covid hat erneut ein Schlaglicht auf die Bedeutung von räumlichen Faktoren für Fragen von Gesundheit und sozialer Gerechtigkeit geworfen. In Stadtplanung und Public Health wird neuerdings verstärkt ein Setting-Ansatz propagiert, der die Bedeutung von Nachbarschaft, räumlichem Umfeld und Umweltfaktoren für Gesundheit und Wohlergehen unterstreicht. Berlin hat bereits 2016 Umweltgerechtigkeit zu einer Zielvorgabe gemacht und nimmt hier bundes- und europaweit eine Vorreiterrolle ein. Auch die feministischen Debatten um Care und Sorgearbeit werden in den vergangenen Jahren verstärkt in der Stadtforschung, Raumplanung und Architektur rezipiert. Zugleich zeigt sich, dass die Messung, Kategorisierung und sozialräumliche Verortung von Strukturen, Bedingungen und Prozessen auf dem Feld der Gesundheitsforschung mit großen Herausforderungen verbunden ist. 

In dem Seminar wollen wir uns zunächst in die aktuelle Literatur einlesen (Environmental Justice, Kritische Sozialepidemiologie, Kritische Kartographie, stadtsoziologische Care-Ansätze) und mit den konzeptionellen und empirischen Schwierigkeiten auseinandersetzen. Auf dieser Grundlage wollen wir dann eigene mediale Formate entwickeln und erstellen, die das Thema Umweltgerechtigkeit für eine breitere Öffentlichkeit an greifbaren Beispielen zugänglich und verständlich machen, und dabei auch die impliziten Voraussetzungen kritisch reflektieren. Denkbar wäre unter anderem die Konzeption einer Wanderausstellung in den Berliner Stadtteilbibliotheken oder auch die Zusammenstellung einer Handreichung für Lehrkräfte oder politische Bildner*innen. 

Das Seminar wird im co-teaching Format unterrichtet und wendet sich vor allem an Studierende der Geographie und der Sozialwissenschaften. 


## Literatur zum Einstieg {.unlisted .unnumbered}

- Dzudzek, Iris und Anke Strüver. 2020. Urbane Gesundheitsgerechtigkeit. *Geographische Zeitschrift*. doi: [10.25162/gz-2020-0005](https://doi.org/10.25162/gz-2020-0005) .
- Gabauer, Angelika et al (2022): *Care and the City. Encounters with Urban Studies*, Routledge. 
- Orangotango. 2018. *This is not an Atlas. A Global Collection of Counter-Cartographies*. Bielefeld: transcript.

