# Kontext {.unnumbered}

## 5. Sitzung am 23.05. | Berlin I Gesundheit bottom-up - Exkursion Gesundheitszentrum {.unnumbered}


### Textarbeit {.unnumbered}

**Lesetext für Alle**

- Plädoyer für eine Ausweitung kritischer Stadtforschung auf das Themenfeld Gesundheit. Gesundheit und Krankheit als verkörperte Formen gesellschaftlicher Macht- und Ungleichheitsverhältnisse begreifen:

  Bůžek, Richard, Iris Dzudzek, Susanne Hübl und Lisa Kamphaus. [-@Buzek22Wenn-die]. Wenn die Verhältnisse unter die Haut gehen. *sub\\urban. zeitschrift für kritische stadtforschung* 10, Nr. 1/2. doi: 10.36900/suburban.v10i1/2.702.

### Projektarbeit {.unnumbered}

- Vor-Ort-Begehung (angefr. Angela)



## 6. Sitzung am 30.05. | Berlin II Gesundheit top-down - Atlas Umweltgerechtigkeit {.unnumbered}

### Textarbeit  {.unnumbered}

**Fallbeispiel Umweltgerechtigkeit**

Debatte um Umweltgerechtigkeit am Beispiel Berlin

- Plattform Umweltgerechtigkeit in Berlin – [https://www.umweltgerechtigkeit-berlin.de](https://www.umweltgerechtigkeit-berlin.de)
- Böhme, Christa und Thomas Franke. [-@Bohme21Umweltge]. Umweltgerechtigkeit und Städtebauförderung. *vhw FWS* 2: 71--74.

### Projektarbeit {.unnumbered}

- Themen der Projektgruppen festlegen
- Rahmen diskutieren


## Sitzung am 06.06 entfällt (Pfingsten) {.unnumbered}
