---
output:
  word_document: default
  html_document: default
---
# Projekt {.unnumbered}


## 7. Sitzung am 13.06. |  eigenständige Projektarbeit {.unnumbered}
-- _Keine Präsenzsitzung_ --

### Projektarbeit {.unnumbered}

- eigenständige Forschung / Recherche

## 8. Sitzung am 20.06. |  Werkstattsitzung  {.unnumbered}

### Projektwerkstatt {.unnumbered}
- Vorstellung des aktuellen Stands in Einzelgesprächen der Gruppen mit den Dozenten

## 9. Sitzung am 27.06. | eigenständige Projektarbeit {.unnumbered}
-- _Keine Präsenzsitzung_ --

### Projektarbeit {.unnumbered}

- eigenständige Forschung / Recherche


## 10. Sitzung am 04.07. | Präsentation Gruppe 1, 2 und 3  {.unnumbered}


### Projektarbeit {.unnumbered}

- Präsentation Gruppe 1
- Präsentation Gruppe 2
- Präsentation Gruppe 3


## 11. Sitzung am 11.07. | Präsentation Gruppe 4, 5 und 6 {.unnumbered}


### Projektarbeit {.unnumbered}

- Präsentation Gruppe 4
- Präsentation Gruppe 5
- Präsentation Gruppe 6


## 12. Sitzung am 18.07. | Abschlusssitzung {.unnumbered}


Zusammenfassung, Reflexion, Planung der Projektarbeiten
